apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: defender-secrets
  namespace: prisma-cloud-defender
spec:
  provider: gcp
  parameters:
    secrets: |
      - resourceName: "projects/{GCP_PROJECT}/secrets/defender-service-parameter/versions/latest"
        path: "service-parameter"
      - resourceName: "projects/{GCP_PROJECT}/secrets/defender-ca/versions/latest"
        path: "ca.pem"
      - resourceName: "projects/{GCP_PROJECT}/secrets/defender-client-cert/versions/latest"
        path: "client-cert.pem"
      - resourceName: "projects/{GCP_PROJECT}/secrets/defender-client-key/versions/latest"
        path: "client-key.pem"
      - resourceName: "projects/{GCP_PROJECT}/secrets/defender-admission-cert/versions/latest"
        path: "admission-cert.pem"
      - resourceName: "projects/{GCP_PROJECT}/secrets/defender-admission-key/versions/latest"
        path: "admission-key.pem"
      - resourceName: "projects/{GCP_PROJECT}/secrets/defender-install-bundle/versions/latest"
        path: "install-bundle"
  secretObjects:
  - secretName: defender-secrets
    type: Opaque
    data: 
    - objectName: install-bundle
      key: install-bundle
